version: '3'
services:
  app:
    build: .
    ports:
      - "80:80"
      - "8080:8080"
    environment:
      NODE_ENV: production



  # # Frontend Service (React)
  # web:
  #   build:
  #     context: ./web
  #     dockerfile: Dockerfile
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - backend

  # # Backend Service (Node.js)
  # backend:
  #   build:
  #     context: ./company-portal
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     - NODE_ENV=production